### ISSUE TITLE
Memory categorization is failing in OpenMemory due to incompatible OpenAI client method

### ISSUE THREAD

**Issue by ryanrozich** [mem0ai/mem0#2993]
## Problem
Memory categorization is completely failing in OpenMemory. When memories are created, the system cannot assign categories to them, which breaks the memory organization and filtering features.

## Error Message
```
'Completions' object has no attribute 'with_response_format'
```

## Impact
- Memories cannot be automatically categorized
- Users cannot filter memories by category
- The memory organization system is non-functional

## Root Cause
The categorization code in `/openmemory/api/app/utils/categorization.py` uses `with_response_format()` which doesn't exist in the OpenAI Python client. The code appears to have been written for a non-existent API method.

### Solution 1: Backwards Compatible Code Fix (PR #2994)
**Approach**: Modify the code to work with the current OpenAI client v1.88.0

**Changes**:
- Uses `response_format={"type": "json_object"}` 
- Implements manual JSON parsing
- No dependency changes needed

**Pros**:
- ✅ Works immediately 
- ✅ No dependency updates required
- ✅ Zero risk to other components
- ✅ Already tested and working

**Cons**:
- More verbose code
- Manual parsing instead of Pydantic

**Status**: ✅ Ready to merge - PR #2994

### Solution 2: Update Dependencies & Fix API Usage (PR #3005)
**Approach**: Update to newer OpenAI client and fix the incorrect API method

**Changes**:
- Adds `openai>=1.40.0` to requirements
- Corrects API from `with_response_format()` to `beta.chat.completions.parse()`
- Bonus: Removes hardcoded API key for security

**Pros**:
- ✅ Uses proper OpenAI API methods
- ✅ Cleaner code with Pydantic parsing
- ✅ Better long-term maintainability
- ✅ Includes security improvement

**Cons**:
- Requires dependency update
- May need compatibility testing

**Status**: ✅ Ready to merge - PR #3005

## Testing Results
Both solutions have been tested successfully:
- ✅ Docker builds without errors
- ✅ Memory creation works
- ✅ Categories are created successfully
- ✅ No categorization errors in logs

## Recommendation
Both PRs solve the problem effectively. Choose based on your preference:
- **Want immediate fix with no dependencies?** → Use PR #2994
- **Want cleaner code with proper API usage?** → Use PR #3005

Either solution will fix the broken categorization system.
