### PR TITLE
fix: Fix memory categorization by updating dependencies and correcting API usage

### LINKED ISSUE #2993: Memory categorization is failing in OpenMemory due to incompatible OpenAI client method
## Problem
Memory categorization is completely failing in OpenMemory. When memories are created, the system cannot assign categories to them, which breaks the memory organization and filtering features.

## Error Message
```
'Completions' object has no attribute 'with_response_format'
```

## Impact
- Memories cannot be automatically categorized
- Users cannot filter memories by category
- The memory organization system is non-functional

## Root Cause
The categorization code in `/openmemory/api/app/utils/categorization.py` uses `with_response_format()` which doesn't exist in the OpenAI Python client. The code appears to have been written for a non-existent API method.

### Solution 1: Backwards Compatible Code Fix (PR #2994)
**Approach**: Modify the code to work with the current OpenAI client v1.88.0

**Changes**:
- Uses `response_format={"type": "json_object"}` 
- Implements manual JSON parsing
- No dependency changes needed

**Pros**:
- ✅ Works immediately 
- ✅ No dependency updates required
- ✅ Zero risk to other components
- ✅ Already tested and working

**Cons**:
- More verbose code
- Manual parsing instead of Pydantic

**Status**: ✅ Ready to merge - PR #2994

### Solution 2: Update Dependencies & Fix API Usage (PR #3005)
**Approach**: Update to newer OpenAI client and fix the incorrect API method

**Changes**:
- Adds `openai>=1.40.0` to requirements
- Corrects API from `with_response_format()` to `beta.chat.completions.parse()`
- Bonus: Removes hardcoded API key for security

**Pros**:
- ✅ Uses proper OpenAI API methods
- ✅ Cleaner code with Pydantic parsing
- ✅ Better long-term maintainability
- ✅ Includes security improvement

**Cons**:
- Requires dependency update
- May need compatibility testing

**Status**: ✅ Ready to merge - PR #3005

## Testing Results
Both solutions have been tested successfully:
- ✅ Docker builds without errors
- ✅ Memory creation works
- ✅ Categories are created successfully
- ✅ No categorization errors in logs

## Recommendation
Both PRs solve the problem effectively. Choose based on your preference:
- **Want immediate fix with no dependencies?** → Use PR #2994
- **Want cleaner code with proper API usage?** → Use PR #3005

Either solution will fix the broken categorization system.

### PR DESCRIPTION
**Pull request by ryanrozich**
## Summary
- Updates OpenAI client dependency to >= 1.40.0
- Corrects the API method from non-existent `with_response_format()` to `beta.chat.completions.parse()`
- Removes hardcoded API key from docker-compose.yml for security

## Details
This PR fixes the memory categorization failure by:

1. **Updating dependencies**: Adding `openai>=1.40.0` to requirements.txt to ensure we have structured outputs support
2. **Correcting API usage**: The code was using `client.chat.completions.with_response_format()` which doesn't exist. The correct method is `client.beta.chat.completions.parse()`
3. **Security fix**: Replaced hardcoded OpenAI API key with environment variable reference

## Test Results
✅ Built Docker container with updated dependencies
✅ Verified OpenAI v1.90.0 is installed
✅ Memory creation works without errors
✅ Categories are successfully created: "entertainment", "preferences"
✅ No categorization errors in logs

## Alternative Solution
PR #2994 provides a backwards-compatible approach that works with older OpenAI versions if updating dependencies is not desired.

Fixes #2993

🤖 Generated with [Claude Code](https://claude.ai/code)

### CODE REVIEW

**Comment by ryanrozich** [comment]
## Important Note: Using Beta API Endpoint

This PR uses `client.beta.chat.completions.parse()` for structured outputs. Here's why and what alternatives to consider:

### Why `beta.chat.completions.parse()`?

1. **It's the only method that supports Pydantic models directly** - The original code was trying to use `with_response_format()` which doesn't exist
2. **Returns parsed Pydantic objects** - You get `completion.choices[0].message.parsed` as a Pydantic object, not just JSON
3. **Cleaner code** - No need to manually parse JSON responses

### The "Beta" Consideration

- This is marked as beta by OpenAI, meaning the API might change in future versions
- However, it's the official OpenAI method for Pydantic-based structured outputs
- Many production applications are using it successfully

### Alternative Approaches

If you prefer to avoid beta APIs, you could:

**Option 1: Use stable API with JSON schema** (more code changes required)
```python
# Convert Pydantic model to JSON schema
completion = openai_client.chat.completions.create(
    model="gpt-4o-mini",
    messages=messages,
    temperature=0,
    response_format={
        "type": "json_schema",
        "json_schema": {
            "name": "memory_categories",
            "schema": MemoryCategories.model_json_schema(),
            "strict": True
        }
    }
)
# Then manually parse: json.loads(completion.choices[0].message.content)
```

**Option 2: Use the backwards-compatible approach** (PR #2994)
- Avoids beta APIs entirely
- Works with older OpenAI client versions
- Manual JSON parsing

### Recommendation

The beta API is stable enough for production use and is the recommended approach by OpenAI for Pydantic models. However, if you have strict policies against beta APIs, PR #2994 provides a non-beta alternative.

### References
- [OpenAI Structured Outputs Documentation](https://platform.openai.com/docs/guides/structured-outputs/)
- [OpenAI Python SDK Issue #1763](https://github.com/openai/openai-python/issues/1763)

**Review by whysosaket — APPROVED** [review]

**Comment by whysosaket** [comment]
Hey @ryanrozich, have reverted the changes in docker-compose file, needs more testing there to not breaking OpenMemory for existing users
