### ISSUE TITLE
Embedchain upgrade to latest version error

### ISSUE THREAD

**Issue by Rainismer** [mem0ai/mem0#2027]
### 🐛 Describe the bug

Using embedchain version 0.1.124 everything works fine, but when upgrading to 0.1.125, chroma errors occur.

**TypeError: SegmentAPI.get_or_create_collection() got an unexpected keyword argument 'embedding_function'**

**Comment by Rainismer** [comment]
@AbhigyaWangoo Thank you for your reply, but it doesn't work for me.

**Comment by AbhigyaWangoo** [comment]
What specifically won't work for you?

**Comment by Rainismer** [comment]
@AbhigyaWangoo 
![image](https://github.com/user-attachments/assets/4aaf90de-1c34-4cf9-8f41-b7024ab21bd0)
